/**
 * The standard output contract for bill data extraction.
 * All providers produce this shape. The orchestration layer
 * and database only work with this type.
 *
 * This is a CODE abstraction, not a DB model. It defines what
 * provider code modules return. DB types are generated by Supabase.
 */
export interface ExtractionResult {
  provider: {
    profileId: string         // provider_invoice_profiles.id (links to DB)
    companyName: string
    taxId: string             // company tax ID (e.g., CNPJ in Brazil, RFC in Mexico)
    category: ProviderCategory
  }
  customer: {
    /** Customer name as printed on the bill */
    name: string
    /** Customer tax ID as printed on the bill */
    taxId: string
    taxIdType: TaxIdType
    countryCode: string       // ISO 3166-1 alpha-2 (e.g., 'BR')
    /** Provider-specific account identifier (installation number, account number, etc.) */
    accountNumber: string
  }
  billing: {
    referenceMonth: string    // YYYY-MM (normalized)
    dueDate: string           // YYYY-MM-DD (normalized)
    amountDue: number         // integer minor units (centavos)
    currency: string          // 'BRL'
  }
  /** Usage/consumption data — optional, varies by provider type */
  consumption?: {
    value: number
    unit: string              // 'kWh', 'm³', 'GB', etc.
  }
  payment: {
    linhaDigitavel?: string
    pixPayload?: string
  }
  confidence: ExtractionConfidence
  rawSource: ExtractionSource
}

export type ExtractionSource = 'pdf' | 'api' | 'dda' | 'ocr' | 'web-scrape' | 'email'

/**
 * Per-field confidence with separate extraction and validation dimensions.
 *
 * Extraction confidence: "did we read the document correctly?"
 * Validation confidence: "does the extracted data match reality?"
 *
 * These are independent signals. A field can have high extraction confidence
 * (parser found it cleanly) but low validation confidence (API returned a
 * different value). Or high extraction + no validation (no second source).
 *
 * Status routing is threshold-based per field, not a single composite score.
 */
export type FieldStatus = 'confirmed' | 'high' | 'needs-review' | 'failed'

export interface FieldConfidence {
  /** 0-1: how sure are we the parser read this correctly? */
  extraction: number
  /** 0-1: how sure are we this matches reality? null if not validated */
  validation?: number
  /** Which source was used for validation */
  validationSource?: string   // 'api', 'web', 'barcode-math', etc.
  /** Routing status derived from extraction + validation */
  status: FieldStatus
}

export interface ExtractionConfidence {
  fields: Record<string, FieldConfidence>
  source: {
    method: ExtractionSource
    /** Base reliability score for this source method (e.g., api=0.95, pdf=0.8) */
    methodScore: number
  }
  summary: {
    totalFields: number
    confirmed: number
    high: number
    needsReview: number
    failed: number
    /** True if zero needs-review and zero failed — can be processed without human */
    autoAcceptable: boolean
  }
}

export type ProviderCategory =
  | 'electricity'
  | 'water'
  | 'gas'
  | 'internet'
  | 'condo'
  | 'sewer'
  | 'insurance'
  | 'other'

export type ProviderProfileStatus = 'draft' | 'active' | 'deprecated'

/**
 * Tax ID types by country.
 * Brazil: 'cpf' (individuals), 'cnpj' (businesses)
 * Extensible for other countries.
 */
export type TaxIdType = 'cpf' | 'cnpj' | string

export interface ProviderCapabilities {
  extraction: boolean
  apiLookup: boolean
  validation: boolean
  paymentStatus: boolean
}

export interface ValidationResult {
  valid: boolean
  source: 'api' | 'web' | 'barcode'
  discrepancies: Array<{
    field: string
    extracted: string | number
    expected: string | number
  }>
}

export interface PaymentStatus {
  paid: boolean
  paidDate?: string           // YYYY-MM-DD
  paidAmount?: number         // integer minor units
  source: 'provider-api' | 'open-finance' | 'dda' | 'user-confirmed' | 'provider-web-scrape'
  /** User ID when source is 'user-confirmed' */
  confirmedBy?: string
}
